### ISSUE TITLE
Setting "List of Exclusive Airports to Display" to blank broke everything!

### ISSUE THREAD

**Issue by peepsnet** [markyharris/livesectional#14]
Ok I deleted everything in the field via the WebUI as the "Settings Description" discribe.

`Subset list of airports to display on the OLED's. These airports must be in the airports file. Leave blank if not needed. Setting above must be set to 'Yes'. Note: Must be in this format; ['KFLG', 'KBOS', 'KLAS', 'KDEN']`

This stored noting in the config.py for the value of exclusive_list and the app would not run. 

> python3 webapp.py
> Traceback (most recent call last):
>   File "webapp.py", line 47, in <module>
>     import config
>   File "/NeoSectional/config.py", line 78
>     exclusive_list =
>                     ^
> SyntaxError: invalid syntax

`

It seems there needs to be a validity check for the data before it is submitted to the config.py so only valid values are stored. 

I had to manually add "[]" to the config.py to correct the error.

**Comment by markyharris** [comment]
You are right. I'll add the instruction to have at least the '[ ]' in the field. Also, as long as the previous setting is set to 'No' then this list is ignored, and deleting the example airports is not necessary.
Thanks for the input. - Mark
