### ISSUE TITLE
How to start from Git Clone

### ISSUE THREAD

**Issue by peepsnet** [markyharris/livesectional#8]
I have cloned the repo on my PI.

What do I run to start it??

**Comment by markyharris** [comment]
Hi, the easiest way to get started is to download the full image here; https://drive.google.com/file/d/12EYluApoyiM3Svc7o0_MOzwxesgSOjh4/view?usp=sharing

The image has all the needed dependencies installed. Other wise you would have to manually install what is needed I haven't yet setup a dependency file here to help with this. 

Once you have the image in place, then you can download the latest version of each file from here if you would like. - Mark

**Comment by peepsnet** [comment]
Ok...
I see...

I was hoping to use an existing RPI without formatting the SD card.

**Comment by markyharris** [comment]
If you don't mind playing with installing the dependencies, Then run this;
sudo python3 /NeoSectional/webapp.py

This will allow you to open the web interface at http://yourip:5000
From here you can set up the settings and airports. Then from the web interface you can start and stop the map from the 'Map Settings' menu.

My only concern, as mentioned is if your image already has the necessary dependencies. If so, great. If not you can install them manually. Please let us know how it goes if you do it manually. - Mark

**Comment by peepsnet** [comment]
Got it working. 

if I git clone it it created a dir called "livesectional"

It seems you hardcoded the directory as /NeoSectional/ so I re cloned the repo via:
`git clone https://github.com/markyharris/livesectional.git /NeoSectional`
to create the file in the root

I needed to add about 4 to 6 modules
`sudo pip3 install flask`
They were evident as I tried to run the webapp.py

needed to use this fix:
`sudo apt-get install libatlas-base-dev`
libf77blas.so.3: cannot open shared object file: No such file or directory
https://numpy.org/devdocs/user/troubleshooting-importerror.html

then is all ran fine

**Comment by markyharris** [comment]
Very good info. This is the first time that its been installed in this manner (that I'm aware of). So thank you for this information. I'm still learning GitHub and will eventually get a requirements.txt file set up with the necessary dependencies. - Mark

**Comment by peepsnet** [comment]
After clicking on many of the WebUI links it did break again and I found more modules I needed to add. No issue was beyond a simple google search for the answer!

There was an issue when I enabled the LED/OLED support. 
The script began to hang because there is no O/LED connected. 
I had to change the config.py file manually because the webapp would hang 
It would seem if a user turned on the support for O/LED without having the device attached or attached wrong there would be an issue.

**Comment by markyharris** [comment]
Yes, you are correct. There a few settings that can conflict with each other. I'd love to hear your ideas on eliminating some of these issues. 
Full disclosure; a year ago, I knew nothing about RPi's and Python. So this project has taken me into brand new areas in which I'm still learning. So I appreciate the feedback and help, as it will serve to help me in the future. - Mark

**Comment by peepsnet** [comment]
great job!!

Im a programmer by hobby(one of many). I was working on this a few years back and now looking to it again.

**Comment by Abdob** [comment]
Hi @markyharris 

I downloaded the full image you provided here and ran `sudo python3 /NeoSectional/webapp.py`

I got this error message:
urllib.error.HTTPError: HTTP Error 406: Not Acceptable

Has anything changed with the url link?

**Comment by Abdob** [comment]
I got the image from your original response to this issue ^.

The rpi boots into this issue. I haven't set up wifi but it has access to the internet via ethernet.

If wifi is required how do you configure it with command line?

**Comment by Abdob** [comment]
It doesn't work ,  when rebooting it shows the error message so the python app doesn't run:
urllib.error.HTTPError: HTTP Error 406: Not Acceptable

**Comment by markyharris** [comment]
What RPi are you using? There have been some issues with the newest
versions of the RPi4 or the new RPi Zero 2 W devices not liking the LED
library. If you are using one of these then try updating the LED library by
entering the following at the command line;

sudo pip3 install rpi_ws281x -U

www.livesectional.com's support forums has more info on this located at;
https://www.livesectional.com/community/raspberry-pi-questions/connecting-to-rpi-via-safari/#post-1012
Let me know. - Mark

**Comment by Abdob** [comment]
It is the raspberry pi 4, I tried updating the LED library but that didn't help , I can look into the forums
